<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BrxMgd">
      <HintPath>C:\Program Files\Bricsys\BricsCAD V22 pl_PL\BrxMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TD_Mgd">
      <HintPath>C:\Program Files\Bricsys\BricsCAD V22 pl_PL\TD_Mgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="WindowsFormsIntegration" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>
